# Generated by Django 3.2 on 2022-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='title', max_length=100)),
                ('contents', models.CharField(blank=True, db_column='contents', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', max_length=100)),
                ('delete_flag', models.CharField(blank=True, db_column='delete_flag', max_length=100)),
                ('public_flag', models.CharField(blank=True, db_column='public_flag', max_length=100)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_column='user', max_length=100)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', max_length=100)),
                ('delete_flag', models.CharField(blank=True, db_column='delete_flag', max_length=100)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='goods_design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_designs')),
                ('image_selected', models.CharField(blank=True, db_column='image_selected', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at', max_length=100)),
                ('delete_flag', models.CharField(blank=True, db_column='delete_flag', max_length=100)),
            ],
            options={
                'db_table': 'goods_design',
            },
        ),
        migrations.CreateModel(
            name='goods_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload_image')),
                ('purchased_date', models.DateTimeField(blank=True, db_column='purchased_date', max_length=100)),
                ('quality', models.CharField(blank=True, db_column='quality', max_length=100)),
                ('material', models.CharField(blank=True, db_column='material', max_length=100)),
                ('goods_type', models.CharField(blank=True, db_column='goods_type', max_length=100)),
                ('style', models.CharField(blank=True, db_column='style', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at', max_length=100)),
                ('delete_flag', models.CharField(blank=True, db_column='delete_flag', max_length=100)),
            ],
            options={
                'db_table': 'goods_info',
            },
        ),
        migrations.CreateModel(
            name='goods_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_column='user', max_length=100)),
                ('designer', models.CharField(blank=True, db_column='designer', max_length=100)),
                ('design_code', models.IntegerField(blank=True, db_column='design_code', null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='result')),
                ('title', models.CharField(blank=True, db_column='title', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at', max_length=100)),
                ('delete_flag', models.CharField(blank=True, db_column='delete_flag', max_length=100)),
            ],
            options={
                'db_table': 'goods_result',
            },
        ),
    ]
