# Generated by Django 3.2 on 2022-02-08 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_info',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='goods_design',
            name='info',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.goods_info', verbose_name='info'),
        ),
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.board', verbose_name='board'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
