# Generated by Django 3.2 on 2022-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_info',
            name='size',
            field=models.CharField(blank=True, db_column='size', max_length=100),
        ),
        migrations.AddField(
            model_name='goods_info',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=100),
        ),
    ]
