# Generated by Django 3.2 on 2022-02-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220219_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_list',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_info', to='api.goods_info'),
        ),
    ]
