# Generated by Django 3.2 on 2022-02-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs'),
        ),
    ]
