# Generated by Django 3.2 on 2022-02-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_goods_result_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_result',
            name='title',
        ),
        migrations.AddField(
            model_name='goods_result',
            name='title_new',
            field=models.CharField(blank=True, db_column='title_new', max_length=100),
        ),
    ]
