# Generated by Django 3.2 on 2022-02-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goods_design_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_design',
            name='image_path',
        ),
    ]
