# Generated by Django 3.2 on 2022-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_request_list_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_design',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='goods_info',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='goods_result',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='goods_design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='goods_result',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='request_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='request_list',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일'),
        ),
    ]
