# Generated by Django 3.2 on 2022-02-01 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_goods_design_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_info',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='goods_result',
            name='result_path',
        ),
        migrations.AddField(
            model_name='goods_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image'),
        ),
        migrations.AddField(
            model_name='goods_result',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=100),
        ),
        migrations.AddField(
            model_name='goods_result',
            name='design_code',
            field=models.IntegerField(blank=True, db_column='design_code', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='goods_result',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='result'),
        ),
        migrations.AddField(
            model_name='goods_result',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='goods_design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_designs'),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(db_column='phone_no', default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, db_column='user_type', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
