# Generated by Django 3.2 on 2022-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220210_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_info',
            name='material',
        ),
        migrations.RemoveField(
            model_name='goods_info',
            name='quality',
        ),
        migrations.AddField(
            model_name='goods_info',
            name='deadline',
            field=models.DateTimeField(blank=True, db_column='deadline', max_length=100, null=True),
        ),
    ]
