# Generated by Django 3.2 on 2022-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220219_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_list',
            name='contents',
        ),
        migrations.AddField(
            model_name='request_list',
            name='cost',
            field=models.IntegerField(db_column='cost', null=True),
        ),
        migrations.AddField(
            model_name='request_list',
            name='designer_address',
            field=models.CharField(blank=True, db_column='designer_address', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request_list',
            name='requests',
            field=models.CharField(blank=True, db_column='requests', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request_list',
            name='user_address',
            field=models.CharField(blank=True, db_column='user_address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request_list',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=100, null=True),
        ),
    ]
