# Generated by Django 3.2 on 2022-02-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220201_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_result',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at', max_length=100),
        ),
        migrations.AddField(
            model_name='goods_result',
            name='delete_flag',
            field=models.CharField(blank=True, db_column='delete_flag', max_length=100),
        ),
        migrations.AlterField(
            model_name='goods_design',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at', max_length=100),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at', max_length=100),
        ),
    ]
