# Generated by Django 3.2 on 2022-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220219_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_list',
            name='chest',
            field=models.IntegerField(db_column='chest', null=True),
        ),
        migrations.AddField(
            model_name='request_list',
            name='length',
            field=models.IntegerField(db_column='length', null=True),
        ),
        migrations.AddField(
            model_name='request_list',
            name='shoulder_width',
            field=models.IntegerField(db_column='shoulder_width', null=True),
        ),
        migrations.AddField(
            model_name='request_list',
            name='sleeve_length',
            field=models.IntegerField(db_column='sleeve_length', null=True),
        ),
    ]
