# Generated by Django 3.2 on 2022-02-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220211_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_info',
            name='image_results',
            field=models.ImageField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='goods_info',
            name='transform_flag',
            field=models.CharField(blank=True, db_column='transform_flag', max_length=100),
        ),
    ]
