# Generated by Django 3.2 on 2022-02-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220213_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='transform_flag',
            field=models.CharField(blank=True, db_column='transform_flag', default='0', max_length=100),
        ),
    ]
