# Generated by Django 3.2 on 2022-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220219_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='purchased_date',
            field=models.DateTimeField(blank=True, db_column='purchased_date', max_length=100, null=True),
        ),
    ]
