# Generated by Django 3.2 on 2022-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_goods_info_transform_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_info',
            name='designer',
            field=models.CharField(blank=True, db_column='designer', max_length=100),
        ),
        migrations.AddField(
            model_name='goods_info',
            name='title_changed',
            field=models.CharField(blank=True, db_column='title_changed', max_length=100),
        ),
    ]
