# Generated by Django 3.2 on 2022-02-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20220213_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='title', max_length=100)),
                ('contents', models.CharField(blank=True, db_column='contents', max_length=100)),
                ('designer', models.CharField(blank=True, db_column='designer', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', max_length=100)),
                ('delete_flag', models.CharField(blank=True, db_column='delete_flag', max_length=100)),
                ('public_flag', models.CharField(blank=True, db_column='public_flag', max_length=100)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'request_list',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.request_list', verbose_name='board'),
        ),
        migrations.DeleteModel(
            name='board',
        ),
    ]
